#loc = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":43:0)
module {
  tt.func public @save_cache_to_buffer_with_mask(%arg0: !tt.ptr<i8> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":43:0), %arg1: !tt.ptr<i8> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":43:0), %arg2: !tt.ptr<i8> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":43:0), %arg3: !tt.ptr<i64> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":43:0), %arg4: !tt.ptr<i8> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":43:0), %arg5: !tt.ptr<i8> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":43:0)) attributes {noinline = false} {
    %cst = arith.constant dense<0> : tensor<15xi8> loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %cst_0 = arith.constant dense<0> : tensor<15xi32> loc(#loc1)
    %cst_1 = arith.constant dense<1> : tensor<15xi32> loc(#loc1)
    %c0_i32 = arith.constant 0 : i32 loc(#loc1)
    %c1_i32 = arith.constant 1 : i32 loc(#loc1)
    %cst_2 = arith.constant dense<150> : tensor<15xi32> loc(#loc1)
    %cst_3 = arith.constant dense<10> : tensor<15xi32> loc(#loc1)
    %c10_i32 = arith.constant 10 : i32 loc(#loc1)
    %cst_4 = arith.constant dense<5> : tensor<15xi32> loc(#loc1)
    %c5_i32 = arith.constant 5 : i32 loc(#loc1)
    %c15_i32 = arith.constant 15 : i32 loc(#loc1)
    %0 = tt.get_program_id x : i32 loc(#loc2)
    %1 = arith.muli %0, %c15_i32 : i32 loc(#loc3)
    %2 = tt.make_range {end = 15 : i32, start = 0 : i32} : tensor<15xi32> loc(#loc4)
    %3 = tt.splat %1 : i32 -> tensor<15xi32> loc(#loc5)
    %4 = arith.addi %3, %2 : tensor<15xi32> loc(#loc5)
    %5 = arith.divsi %4, %cst_4 : tensor<15xi32> loc(#loc6)
    %6 = arith.remsi %4, %cst_4 : tensor<15xi32> loc(#loc7)
    %7 = arith.muli %5, %cst_3 : tensor<15xi32> loc(#loc8)
    %8 = arith.addi %7, %6 : tensor<15xi32> loc(#loc9)
    %9 = arith.cmpi slt, %8, %cst_2 : tensor<15xi32> loc(#loc10)
    %10 = arith.select %9, %cst_1, %cst_0 : tensor<15xi1>, tensor<15xi32> loc(#loc11)
    %11 = tt.splat %arg4 : !tt.ptr<i8> -> tensor<15x!tt.ptr<i8>> loc(#loc12)
    %12 = tt.addptr %11, %4 : tensor<15x!tt.ptr<i8>>, tensor<15xi32> loc(#loc12)
    %13 = arith.trunci %10 : tensor<15xi32> to tensor<15xi8> loc(#loc13)
    tt.store %12, %13 : tensor<15x!tt.ptr<i8>> loc(#loc13)
    scf.for %arg6 = %c0_i32 to %c15_i32 step %c1_i32  : i32 {
      %17 = arith.addi %1, %arg6 : i32 loc(#loc15)
      %18 = tt.addptr %arg5, %17 : !tt.ptr<i8>, i32 loc(#loc16)
      %19 = arith.divsi %17, %c5_i32 : i32 loc(#loc17)
      %20 = arith.muli %19, %c10_i32 : i32 loc(#loc18)
      %21 = arith.remsi %17, %c5_i32 : i32 loc(#loc19)
      %22 = arith.addi %20, %21 : i32 loc(#loc20)
      %23 = arith.trunci %22 : i32 to i8 loc(#loc21)
      tt.store %18, %23 : !tt.ptr<i8> loc(#loc21)
    } loc(#loc14)
    %14 = arith.remsi %0, %c2_i32 : i32 loc(#loc22)
    %15 = arith.cmpi eq, %14, %c0_i32 : i32 loc(#loc23)
    scf.if %15 {
      %17 = tt.splat %arg1 : !tt.ptr<i8> -> tensor<15x!tt.ptr<i8>> loc(#loc25)
      %18 = tt.addptr %17, %8 : tensor<15x!tt.ptr<i8>>, tensor<15xi32> loc(#loc25)
      %19 = tt.load %18, %9, %cst : tensor<15x!tt.ptr<i8>> loc(#loc26)
      %20 = tt.splat %arg0 : !tt.ptr<i8> -> tensor<15x!tt.ptr<i8>> loc(#loc27)
      %21 = tt.addptr %20, %4 : tensor<15x!tt.ptr<i8>>, tensor<15xi32> loc(#loc27)
      tt.store %21, %19 : tensor<15x!tt.ptr<i8>> loc(#loc28)
    } loc(#loc24)
    %16 = arith.cmpi eq, %14, %c1_i32 : i32 loc(#loc29)
    scf.if %16 {
      %17 = tt.splat %arg2 : !tt.ptr<i8> -> tensor<15x!tt.ptr<i8>> loc(#loc31)
      %18 = tt.addptr %17, %8 : tensor<15x!tt.ptr<i8>>, tensor<15xi32> loc(#loc31)
      %19 = tt.load %18, %9, %cst : tensor<15x!tt.ptr<i8>> loc(#loc32)
      %20 = tt.splat %arg0 : !tt.ptr<i8> -> tensor<15x!tt.ptr<i8>> loc(#loc33)
      %21 = tt.addptr %20, %4 : tensor<15x!tt.ptr<i8>>, tensor<15xi32> loc(#loc33)
      tt.store %21, %19 : tensor<15x!tt.ptr<i8>> loc(#loc34)
    } loc(#loc30)
    tt.return loc(#loc35)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":54:28)
#loc3 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":56:30)
#loc4 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":58:32)
#loc5 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":59:28)
#loc6 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":60:29)
#loc7 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":61:28)
#loc8 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":63:20)
#loc9 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":63:36)
#loc10 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":63:53)
#loc11 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":68:27)
#loc12 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":69:19)
#loc13 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":69:26)
#loc14 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":71:22)
#loc15 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":72:30)
#loc16 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":73:24)
#loc17 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":73:45)
#loc18 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":73:38)
#loc19 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":73:61)
#loc20 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":73:55)
#loc21 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":73:29)
#loc22 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":75:17)
#loc23 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":75:22)
#loc24 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":75:7)
#loc25 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":76:36)
#loc26 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":77:12)
#loc27 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":78:30)
#loc28 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":78:37)
#loc29 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":79:22)
#loc30 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":79:7)
#loc31 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":80:36)
#loc32 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":81:12)
#loc33 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":82:30)
#loc34 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":82:37)
#loc35 = loc("/home/coder/workspace/triton-ascend/ascend/examples/pytest_ut/test_linearize_2.py":79:4)
