#loc = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":17:0)
module {
  tt.func public @moe_align_block_size_stage4(%arg0: !tt.ptr<i32> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":17:0), %arg1: !tt.ptr<i32> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":17:0), %arg2: !tt.ptr<i32> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":17:0), %arg3: !tt.ptr<i32> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":17:0), %arg4: !tt.ptr<i32> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":17:0)) attributes {noinline = false} {
    %c4_i32 = arith.constant 4 : i32 loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %c1_i32 = arith.constant 1 : i32 loc(#loc1)
    %0 = tt.get_program_id x : i32 loc(#loc2)
    %1 = tt.addptr %arg4, %0 : !tt.ptr<i32>, i32 loc(#loc3)
    %2 = tt.load %1 : !tt.ptr<i32> loc(#loc4)
    %3 = tt.addptr %1, %c1_i32 : !tt.ptr<i32>, i32 loc(#loc5)
    %4 = tt.load %3 : !tt.ptr<i32> loc(#loc6)
    scf.for %arg5 = %2 to %4 step %c2_i32  : i32 {
      %9 = arith.divsi %arg5, %c2_i32 : i32 loc(#loc8)
      %10 = tt.addptr %arg2, %9 : !tt.ptr<i32>, i32 loc(#loc9)
      tt.store %10, %0 : !tt.ptr<i32> loc(#loc10)
    } loc(#loc7)
    %5 = arith.muli %0, %c2_i32 : i32 loc(#loc11)
    %6 = arith.addi %5, %c2_i32 : i32 loc(#loc12)
    %7 = arith.minsi %6, %c4_i32 : i32 loc(#loc13)
    %8 = tt.addptr %arg3, %5 : !tt.ptr<i32>, i32 loc(#loc14)
    scf.for %arg5 = %5 to %7 step %c1_i32  : i32 {
      %9 = tt.addptr %arg0, %arg5 : !tt.ptr<i32>, i32 loc(#loc16)
      %10 = tt.load %9 : !tt.ptr<i32> loc(#loc17)
      %11 = tt.addptr %8, %10 : !tt.ptr<i32>, i32 loc(#loc18)
      %12 = tt.load %11 : !tt.ptr<i32> loc(#loc19)
      %13 = tt.addptr %arg4, %10 : !tt.ptr<i32>, i32 loc(#loc20)
      %14 = tt.load %13 : !tt.ptr<i32> loc(#loc21)
      %15 = arith.addi %12, %14 : i32 loc(#loc22)
      %16 = tt.addptr %arg1, %15 : !tt.ptr<i32>, i32 loc(#loc23)
      tt.store %16, %arg5 : !tt.ptr<i32> loc(#loc24)
      %17 = arith.addi %12, %c1_i32 : i32 loc(#loc25)
      tt.store %11, %17 : !tt.ptr<i32> loc(#loc26)
    } loc(#loc15)
    tt.return loc(#loc27)
  } loc(#loc)
} loc(#loc)
#loc1 = loc(unknown)
#loc2 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":28:24)
#loc3 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":29:37)
#loc4 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":29:24)
#loc5 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":30:41)
#loc6 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":30:22)
#loc7 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":32:39)
#loc8 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":33:39)
#loc9 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":33:34)
#loc10 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":33:51)
#loc11 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":35:22)
#loc12 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":38:53)
#loc13 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":38:72)
#loc14 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":40:46)
#loc15 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":38:30)
#loc16 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":39:43)
#loc17 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":39:28)
#loc18 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":40:54)
#loc19 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":40:28)
#loc20 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":41:57)
#loc21 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":41:44)
#loc22 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":41:36)
#loc23 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":42:40)
#loc24 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":42:55)
#loc25 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":43:66)
#loc26 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":43:54)
#loc27 = loc("/home/coder/workspace/sglang-test/moe_align_block_size_stage4/test_moe_align_block_size_stage4.py":38:4)
