#loc = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0)
#loc1 = loc(unknown)
#loc13 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":181:49)
#loc29 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":185:18)
#loc39 = loc(callsite(#loc1 at #loc13))
#loc55 = loc(callsite(#loc1 at #loc29))
module {
  tt.func public @scan_part_min_kernel_bak(%arg0: !tt.ptr<f16> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0), %arg1: !tt.ptr<f16> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0), %arg2: !tt.ptr<i64> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0), %arg3: !tt.ptr<i64> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0), %arg4: !tt.ptr<f32> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0), %arg5: !tt.ptr<i64> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0), %arg6: i32 loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":153:0)) attributes {noinline = false} {
    %cst = arith.constant dense<0x7C00> : tensor<2xf16> loc(#loc1)
    %true = arith.constant true loc(#loc1)
    %cst_0 = arith.constant dense<0> : tensor<2xi64> loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %0 = tt.get_program_id x : i32 loc(#loc2)
    %1 = arith.muli %0, %c2_i32 : i32 loc(#loc3)
    %2 = tt.make_range {end = 2 : i32, start = 0 : i32} : tensor<2xi32> loc(#loc4)
    %3 = tt.splat %1 : i32 -> tensor<2xi32> loc(#loc5)
    %4 = arith.addi %3, %2 : tensor<2xi32> loc(#loc5)
    %5 = tt.splat %arg6 : i32 -> tensor<2xi32> loc(#loc6)
    %6 = arith.cmpi slt, %4, %5 : tensor<2xi32> loc(#loc6)
    %7 = tt.splat %arg0 : !tt.ptr<f16> -> tensor<2x!tt.ptr<f16>> loc(#loc7)
    %8 = tt.addptr %7, %4 : tensor<2x!tt.ptr<f16>>, tensor<2xi32> loc(#loc7)
    %9 = tt.load %8, %6, %cst : tensor<2x!tt.ptr<f16>> loc(#loc8)
    %10 = arith.extf %9 : tensor<2xf16> to tensor<2xf32> loc(#loc9)
    %11 = tt.splat %arg3 : !tt.ptr<i64> -> tensor<2x!tt.ptr<i64>> loc(#loc10)
    %12 = tt.addptr %11, %4 : tensor<2x!tt.ptr<i64>>, tensor<2xi32> loc(#loc10)
    %13 = tt.load %12, %6, %cst_0 : tensor<2x!tt.ptr<i64>> loc(#loc11)
    %14:2 = "tt.scan"(%10, %13) <{axis = 0 : i32, reverse = false}> ({
    ^bb0(%arg7: f32 loc(callsite(#loc1 at #loc13)), %arg8: i64 loc(callsite(#loc1 at #loc13)), %arg9: f32 loc(callsite(#loc1 at #loc13)), %arg10: i64 loc(callsite(#loc1 at #loc13))):
      %21 = arith.cmpf olt, %arg7, %arg9 : f32 loc(#loc70)
      %22 = arith.cmpf oeq, %arg7, %arg9 : f32 loc(#loc71)
      %23 = arith.cmpf une, %arg7, %arg7 : f32 loc(#loc72)
      %24 = arith.cmpf une, %arg9, %arg9 : f32 loc(#loc73)
      %25 = arith.xori %24, %true : i1 loc(#loc74)
      %26 = arith.andi %23, %25 : i1 loc(#loc75)
      %27 = arith.ori %21, %26 : i1 loc(#loc76)
      %28 = arith.andi %23, %24 : i1 loc(#loc77)
      %29 = arith.ori %22, %28 : i1 loc(#loc78)
      %30 = arith.cmpi sgt, %arg8, %arg10 : i64 loc(#loc79)
      %31 = arith.andi %29, %30 : i1 loc(#loc80)
      %32 = arith.ori %27, %31 : i1 loc(#loc81)
      %33 = arith.select %32, %arg7, %arg9 : f32 loc(#loc82)
      %34 = arith.select %32, %arg8, %arg10 : i64 loc(#loc83)
      tt.scan.return %33, %34 : f32, i64 loc(#loc38)
    }) : (tensor<2xf32>, tensor<2xi64>) -> (tensor<2xf32>, tensor<2xi64>) loc(#loc38)
    %15:2 = "tt.reduce"(%10, %13) <{axis = 0 : i32}> ({
    ^bb0(%arg7: f32 loc(callsite(#loc1 at #loc29)), %arg8: i64 loc(callsite(#loc1 at #loc29)), %arg9: f32 loc(callsite(#loc1 at #loc29)), %arg10: i64 loc(callsite(#loc1 at #loc29))):
      %21 = arith.cmpf olt, %arg7, %arg9 : f32 loc(#loc84)
      %22 = arith.cmpf oeq, %arg7, %arg9 : f32 loc(#loc85)
      %23 = arith.cmpf une, %arg7, %arg7 : f32 loc(#loc86)
      %24 = arith.cmpf une, %arg9, %arg9 : f32 loc(#loc87)
      %25 = arith.xori %24, %true : i1 loc(#loc88)
      %26 = arith.andi %23, %25 : i1 loc(#loc89)
      %27 = arith.ori %21, %26 : i1 loc(#loc90)
      %28 = arith.andi %23, %24 : i1 loc(#loc91)
      %29 = arith.ori %22, %28 : i1 loc(#loc92)
      %30 = arith.cmpi sgt, %arg8, %arg10 : i64 loc(#loc93)
      %31 = arith.andi %29, %30 : i1 loc(#loc94)
      %32 = arith.ori %27, %31 : i1 loc(#loc95)
      %33 = arith.select %32, %arg7, %arg9 : f32 loc(#loc96)
      %34 = arith.select %32, %arg8, %arg10 : i64 loc(#loc97)
      tt.reduce.return %33, %34 : f32, i64 loc(#loc54)
    }) : (tensor<2xf32>, tensor<2xi64>) -> (f32, i64) loc(#loc54)
    %16 = tt.splat %arg1 : !tt.ptr<f16> -> tensor<2x!tt.ptr<f16>> loc(#loc30)
    %17 = tt.addptr %16, %4 : tensor<2x!tt.ptr<f16>>, tensor<2xi32> loc(#loc30)
    %18 = arith.truncf %14#0 : tensor<2xf32> to tensor<2xf16> loc(#loc31)
    tt.store %17, %18, %6 : tensor<2x!tt.ptr<f16>> loc(#loc31)
    tt.store %12, %14#1, %6 : tensor<2x!tt.ptr<i64>> loc(#loc32)
    %19 = tt.addptr %arg4, %0 : !tt.ptr<f32>, i32 loc(#loc33)
    tt.store %19, %15#0 : !tt.ptr<f32> loc(#loc34)
    %20 = tt.addptr %arg5, %0 : !tt.ptr<i64>, i32 loc(#loc35)
    tt.store %20, %15#1 : !tt.ptr<i64> loc(#loc36)
    tt.return loc(#loc37)
  } loc(#loc)
} loc(#loc)
#loc2 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":163:24)
#loc3 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":164:19)
#loc4 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":164:45)
#loc5 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":164:32)
#loc6 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":165:20)
#loc7 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":168:21)
#loc8 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":169:23)
#loc9 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":178:31)
#loc10 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":179:36)
#loc11 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":180:30)
#loc12 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":50:30)
#loc14 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":35:21)
#loc15 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":36:23)
#loc16 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":38:29)
#loc17 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":39:29)
#loc18 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":40:32)
#loc19 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":40:28)
#loc20 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":40:16)
#loc21 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":41:29)
#loc22 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":41:17)
#loc23 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":43:31)
#loc24 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":43:21)
#loc25 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":43:12)
#loc26 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":44:35)
#loc27 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":44:69)
#loc28 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":59:8)
#loc30 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":188:21)
#loc31 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":189:23)
#loc32 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":192:31)
#loc33 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":194:37)
#loc34 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":195:31)
#loc35 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":197:53)
#loc36 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":198:39)
#loc37 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan_reduce.py":198:4)
#loc38 = loc(callsite(#loc12 at #loc13))
#loc40 = loc(callsite(#loc14 at #loc12))
#loc41 = loc(callsite(#loc15 at #loc12))
#loc42 = loc(callsite(#loc16 at #loc12))
#loc43 = loc(callsite(#loc17 at #loc12))
#loc44 = loc(callsite(#loc18 at #loc12))
#loc45 = loc(callsite(#loc19 at #loc12))
#loc46 = loc(callsite(#loc20 at #loc12))
#loc47 = loc(callsite(#loc21 at #loc12))
#loc48 = loc(callsite(#loc22 at #loc12))
#loc49 = loc(callsite(#loc23 at #loc12))
#loc50 = loc(callsite(#loc24 at #loc12))
#loc51 = loc(callsite(#loc25 at #loc12))
#loc52 = loc(callsite(#loc26 at #loc12))
#loc53 = loc(callsite(#loc27 at #loc12))
#loc54 = loc(callsite(#loc28 at #loc29))
#loc56 = loc(callsite(#loc14 at #loc28))
#loc57 = loc(callsite(#loc15 at #loc28))
#loc58 = loc(callsite(#loc16 at #loc28))
#loc59 = loc(callsite(#loc17 at #loc28))
#loc60 = loc(callsite(#loc18 at #loc28))
#loc61 = loc(callsite(#loc19 at #loc28))
#loc62 = loc(callsite(#loc20 at #loc28))
#loc63 = loc(callsite(#loc21 at #loc28))
#loc64 = loc(callsite(#loc22 at #loc28))
#loc65 = loc(callsite(#loc23 at #loc28))
#loc66 = loc(callsite(#loc24 at #loc28))
#loc67 = loc(callsite(#loc25 at #loc28))
#loc68 = loc(callsite(#loc26 at #loc28))
#loc69 = loc(callsite(#loc27 at #loc28))
#loc70 = loc(callsite(#loc40 at #loc13))
#loc71 = loc(callsite(#loc41 at #loc13))
#loc72 = loc(callsite(#loc42 at #loc13))
#loc73 = loc(callsite(#loc43 at #loc13))
#loc74 = loc(callsite(#loc44 at #loc13))
#loc75 = loc(callsite(#loc45 at #loc13))
#loc76 = loc(callsite(#loc46 at #loc13))
#loc77 = loc(callsite(#loc47 at #loc13))
#loc78 = loc(callsite(#loc48 at #loc13))
#loc79 = loc(callsite(#loc49 at #loc13))
#loc80 = loc(callsite(#loc50 at #loc13))
#loc81 = loc(callsite(#loc51 at #loc13))
#loc82 = loc(callsite(#loc52 at #loc13))
#loc83 = loc(callsite(#loc53 at #loc13))
#loc84 = loc(callsite(#loc56 at #loc29))
#loc85 = loc(callsite(#loc57 at #loc29))
#loc86 = loc(callsite(#loc58 at #loc29))
#loc87 = loc(callsite(#loc59 at #loc29))
#loc88 = loc(callsite(#loc60 at #loc29))
#loc89 = loc(callsite(#loc61 at #loc29))
#loc90 = loc(callsite(#loc62 at #loc29))
#loc91 = loc(callsite(#loc63 at #loc29))
#loc92 = loc(callsite(#loc64 at #loc29))
#loc93 = loc(callsite(#loc65 at #loc29))
#loc94 = loc(callsite(#loc66 at #loc29))
#loc95 = loc(callsite(#loc67 at #loc29))
#loc96 = loc(callsite(#loc68 at #loc29))
#loc97 = loc(callsite(#loc69 at #loc29))
