#loc = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":97:0)
#loc1 = loc(unknown)
#loc11 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":130:49)
#loc32 = loc(callsite(#loc1 at #loc11))
module {
  tt.func public @scan_part_min_kernel(%arg0: !tt.ptr<f16> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":97:0), %arg1: !tt.ptr<f16> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":97:0), %arg2: !tt.ptr<i64> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":97:0), %arg3: !tt.ptr<i64> {tt.divisibility = 16 : i32} loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":97:0), %arg4: i32 loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":97:0)) attributes {noinline = false} {
    %cst = arith.constant dense<0x7C00> : tensor<2xf16> loc(#loc1)
    %true = arith.constant true loc(#loc1)
    %c2_i32 = arith.constant 2 : i32 loc(#loc1)
    %0 = tt.get_program_id x : i32 loc(#loc2)
    %1 = arith.muli %0, %c2_i32 : i32 loc(#loc3)
    %2 = tt.make_range {end = 2 : i32, start = 0 : i32} : tensor<2xi32> loc(#loc4)
    %3 = tt.splat %1 : i32 -> tensor<2xi32> loc(#loc5)
    %4 = arith.addi %3, %2 : tensor<2xi32> loc(#loc5)
    %5 = tt.splat %arg4 : i32 -> tensor<2xi32> loc(#loc6)
    %6 = arith.cmpi slt, %4, %5 : tensor<2xi32> loc(#loc6)
    %7 = tt.splat %arg0 : !tt.ptr<f16> -> tensor<2x!tt.ptr<f16>> loc(#loc7)
    %8 = tt.addptr %7, %4 : tensor<2x!tt.ptr<f16>>, tensor<2xi32> loc(#loc7)
    %9 = tt.load %8, %6, %cst : tensor<2x!tt.ptr<f16>> loc(#loc8)
    %10 = arith.extf %9 : tensor<2xf16> to tensor<2xf32> loc(#loc9)
    %11:2 = "tt.scan"(%10, %4) <{axis = 0 : i32, reverse = false}> ({
    ^bb0(%arg5: f32 loc(callsite(#loc1 at #loc11)), %arg6: i32 loc(callsite(#loc1 at #loc11)), %arg7: f32 loc(callsite(#loc1 at #loc11)), %arg8: i32 loc(callsite(#loc1 at #loc11))):
      %18 = arith.cmpf olt, %arg5, %arg7 : f32 loc(#loc47)
      %19 = arith.cmpf oeq, %arg5, %arg7 : f32 loc(#loc48)
      %20 = arith.cmpf une, %arg5, %arg5 : f32 loc(#loc49)
      %21 = arith.cmpf une, %arg7, %arg7 : f32 loc(#loc50)
      %22 = arith.xori %21, %true : i1 loc(#loc51)
      %23 = arith.andi %20, %22 : i1 loc(#loc52)
      %24 = arith.ori %18, %23 : i1 loc(#loc53)
      %25 = arith.andi %20, %21 : i1 loc(#loc54)
      %26 = arith.ori %19, %25 : i1 loc(#loc55)
      %27 = arith.cmpi sgt, %arg6, %arg8 : i32 loc(#loc56)
      %28 = arith.andi %26, %27 : i1 loc(#loc57)
      %29 = arith.ori %24, %28 : i1 loc(#loc58)
      %30 = arith.select %29, %arg5, %arg7 : f32 loc(#loc59)
      %31 = arith.select %29, %arg6, %arg8 : i32 loc(#loc60)
      tt.scan.return %30, %31 : f32, i32 loc(#loc31)
    }) : (tensor<2xf32>, tensor<2xi32>) -> (tensor<2xf32>, tensor<2xi32>) loc(#loc31)
    %12 = tt.splat %arg1 : !tt.ptr<f16> -> tensor<2x!tt.ptr<f16>> loc(#loc26)
    %13 = tt.addptr %12, %4 : tensor<2x!tt.ptr<f16>>, tensor<2xi32> loc(#loc26)
    %14 = arith.truncf %11#0 : tensor<2xf32> to tensor<2xf16> loc(#loc27)
    tt.store %13, %14, %6 : tensor<2x!tt.ptr<f16>> loc(#loc27)
    %15 = tt.splat %arg3 : !tt.ptr<i64> -> tensor<2x!tt.ptr<i64>> loc(#loc28)
    %16 = tt.addptr %15, %4 : tensor<2x!tt.ptr<i64>>, tensor<2xi32> loc(#loc28)
    %17 = arith.extsi %11#1 : tensor<2xi32> to tensor<2xi64> loc(#loc29)
    tt.store %16, %17, %6 : tensor<2x!tt.ptr<i64>> loc(#loc29)
    tt.return loc(#loc30)
  } loc(#loc)
} loc(#loc)
#loc2 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":109:24)
#loc3 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":110:19)
#loc4 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":110:45)
#loc5 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":110:32)
#loc6 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":111:20)
#loc7 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":114:21)
#loc8 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":115:23)
#loc9 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":124:31)
#loc10 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":50:30)
#loc12 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":35:21)
#loc13 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":36:23)
#loc14 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":38:29)
#loc15 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":39:29)
#loc16 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":40:32)
#loc17 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":40:28)
#loc18 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":40:16)
#loc19 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":41:29)
#loc20 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":41:17)
#loc21 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":43:31)
#loc22 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":43:21)
#loc23 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":43:12)
#loc24 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":44:35)
#loc25 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":44:69)
#loc26 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":138:21)
#loc27 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":139:23)
#loc28 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":141:37)
#loc29 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":142:31)
#loc30 = loc("/home/coder/workspace/scan/triton-ascend/../../sglang-test/other_test/asccociate_scan/test_cummin_scan.py":144:4)
#loc31 = loc(callsite(#loc10 at #loc11))
#loc33 = loc(callsite(#loc12 at #loc10))
#loc34 = loc(callsite(#loc13 at #loc10))
#loc35 = loc(callsite(#loc14 at #loc10))
#loc36 = loc(callsite(#loc15 at #loc10))
#loc37 = loc(callsite(#loc16 at #loc10))
#loc38 = loc(callsite(#loc17 at #loc10))
#loc39 = loc(callsite(#loc18 at #loc10))
#loc40 = loc(callsite(#loc19 at #loc10))
#loc41 = loc(callsite(#loc20 at #loc10))
#loc42 = loc(callsite(#loc21 at #loc10))
#loc43 = loc(callsite(#loc22 at #loc10))
#loc44 = loc(callsite(#loc23 at #loc10))
#loc45 = loc(callsite(#loc24 at #loc10))
#loc46 = loc(callsite(#loc25 at #loc10))
#loc47 = loc(callsite(#loc33 at #loc11))
#loc48 = loc(callsite(#loc34 at #loc11))
#loc49 = loc(callsite(#loc35 at #loc11))
#loc50 = loc(callsite(#loc36 at #loc11))
#loc51 = loc(callsite(#loc37 at #loc11))
#loc52 = loc(callsite(#loc38 at #loc11))
#loc53 = loc(callsite(#loc39 at #loc11))
#loc54 = loc(callsite(#loc40 at #loc11))
#loc55 = loc(callsite(#loc41 at #loc11))
#loc56 = loc(callsite(#loc42 at #loc11))
#loc57 = loc(callsite(#loc43 at #loc11))
#loc58 = loc(callsite(#loc44 at #loc11))
#loc59 = loc(callsite(#loc45 at #loc11))
#loc60 = loc(callsite(#loc46 at #loc11))
